name: Generate Documentation

on:
  pull_request:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Generate Docs
        run: terraform-docs markdown table --output-file README.md .
      - name: Commit documentation changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update documentation" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
