name: Terraform Format

on:
  pull_request:

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git config --global pull.rebase false

      - name: Fetch and Merge Latest Changes
        run: |
          git fetch origin ${GITHUB_HEAD_REF}
          git merge origin/${GITHUB_HEAD_REF}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Commit formatting changes
        run: |
          git add -A
          git commit -m "Apply terraform fmt changes" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
