name: Terraform Format and Documentation

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Git for Format Job
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Commit formatting changes
        run: |
          git add -A
          git commit -m "Apply terraform fmt changes" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}

  documentation:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
  
      - name: Setup Git for Documentation Job
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
  
      - name: Install terraform-docs
        run: |
          curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.17.0/terraform-docs-v0.17.0-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          sudo mv terraform-docs /usr/local/bin/terraform-docs
  
      - name: Generate Docs
        run: terraform-docs markdown table --output-file README.md .
  
      - name: Commit documentation changes
        run: |
          git add README.md
          git commit -m "Update documentation" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
          
